name: MLflow CI with Docker

on:
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install MLflow
        run: pip install mlflow==2.19.0

      - name: Build Docker Image from MLflow Run
        run: |
          mlflow models build-docker \
            -m "runs:/abb7dbc8575746eda7022fa47837a65f/model"\
            -n telco-churn

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag telco-churn:latest ${{ secrets.DOCKER_USERNAME }}/telco-churn:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn:latest
